name: Deploy to Sakura Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5

        with:
          server: www677.sakura.ne.jp
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./
          server-dir: /home/kei-on/www/12sensyutsu.com/

          exclude: |
            **/.git*
            **/.git*/**
            **/README.md
