name: Deploy to Sakura Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: nwtgck/actions-sftp-deploy@v1.2.2
        with:
          server: www677.sakura.ne.jp
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/home/kei-on/www/12sensyutsu.com/'
          ssh_options: '-o ConnectTimeout=60'
