name: Deploy to Sakura Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: kei-on.sakura.ne.jp
          username: kei-on
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./
          server-dir: ./www/12sensyutsu.com/
